/** Wellness Gym - shared frontend behavior */
const THEME_KEY='wellness_gym_theme';
document.addEventListener('DOMContentLoaded',()=>{initTheme();initNavToggle();initContactForm();initSmoothScroll();initStatCounters();initRevealAnimations();initWorkoutPanel();});
function initTheme(){const saved=localStorage.getItem(THEME_KEY)||'dark';document.documentElement.setAttribute('data-theme',saved);const b=document.querySelector('.theme-toggle');if(b)b.addEventListener('click',()=>{const n=(document.documentElement.getAttribute('data-theme')||'dark')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',n);localStorage.setItem(THEME_KEY,n);});}
function initNavToggle(){const t=document.querySelector('.nav-toggle'),m=document.querySelector('.nav-menu');if(!t||!m)return;t.addEventListener('click',()=>{m.classList.toggle('active');t.classList.toggle('active');document.body.style.overflow=m.classList.contains('active')?'hidden':'';});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m.classList.remove('active');t.classList.remove('active');document.body.style.overflow='';}));}
function initContactForm(){const f=document.querySelector('.contact-form');if(!f)return;f.addEventListener('submit',e=>{const n=f.querySelector('#name'),em=f.querySelector('#email'),msg=f.querySelector('#message');if(!n?.value||!em?.value||!msg?.value){e.preventDefault();showNotification('Please fill in all required fields.','error');}});}
function initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',function(e){const h=this.getAttribute('href');if(!h||h==='#')return;const t=document.querySelector(h);if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});}}));}
function initStatCounters(){const els=document.querySelectorAll('.stat-number[data-target]');els.forEach(el=>{const target=Number(el.dataset.target)||0;let start=null;const run=t=>{if(!start)start=t;const p=Math.min((t-start)/1200,1);el.textContent=Math.floor(p*target).toLocaleString();if(p<1)requestAnimationFrame(run);};requestAnimationFrame(run);});}
function initRevealAnimations(){const els=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('is-visible'));return;}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target);}}),{threshold:.12});els.forEach(e=>o.observe(e));}
const WORKOUT_LIBRARY={
chest:{label:'Chest',description:'Pressing and chest-building work for strength and size.',exercises:[['Barbell Bench Press','https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif','4 sets','6-8 reps'],['Incline Bench Press','https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Barbell-Bench-Press.gif','4 sets','8-10 reps'],['Dumbbell Fly','https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif','3 sets','10-12 reps']]},
back:{label:'Back',description:'Build lat width, thickness and posture.',exercises:[['Pull-Up','https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif','4 sets','6-10 reps'],['Lat Pulldown','https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif','4 sets','8-12 reps'],['Seated Cable Row','https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif','3 sets','10-12 reps']]},
shoulders:{label:'Shoulders',description:'Develop strong, rounded shoulders.',exercises:[['Barbell Shoulder Press','https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Shoulder-Press.gif','4 sets','6-10 reps'],['Lateral Raise','https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif','4 sets','12-15 reps']]},
arms:{label:'Arms',description:'Biceps and triceps volume for balanced arm growth.',exercises:[['Barbell Curl','https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif','4 sets','8-12 reps'],['Triceps Pushdown','https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif','4 sets','10-15 reps']]},
forearms:{label:'Forearms',description:'Grip and forearm strength.',exercises:[['Wrist Curl','https://fitnessprogramer.com/wp-content/uploads/2021/02/Wrist-Curl.gif','3 sets','15 reps'],['Farmers Walk','https://fitnessprogramer.com/wp-content/uploads/2022/02/Farmers-walk_Cardio.gif','4 rounds','30 sec']]},
fatLoss:{label:'Fat Loss',description:'High-density conditioning to raise calorie expenditure.',exercises:[['Burpee Push-Up','https://fitnessprogramer.com/wp-content/uploads/2025/08/Burpee-with-Push-Up.gif','4 rounds','10 reps'],['Shadow Boxing','https://fitnessprogramer.com/wp-content/uploads/2023/09/shadow-boxing-workout.gif','5 rounds','60 sec']]},
weightGain:{label:'Weight Gain',description:'Compound lifts and progressive overload for muscle gain.',exercises:[['Barbell Squat','https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif','5 sets','5-8 reps'],['Barbell Deadlift','https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif','4 sets','4-6 reps'],['Bench Press','https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif','5 sets','5-8 reps']]}}
function initWorkoutPanel(){const buttons=document.getElementById('workoutGroupButtons'),grid=document.getElementById('workoutExerciseGrid'),title=document.getElementById('workoutGroupTitle'),desc=document.getElementById('workoutGroupDescription');if(!buttons||!grid||!title||!desc)return;const keys=Object.keys(WORKOUT_LIBRARY);const render=k=>{const g=WORKOUT_LIBRARY[k]||WORKOUT_LIBRARY.chest;title.textContent=g.label;desc.textContent=g.description;buttons.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.group===k));grid.innerHTML=g.exercises.map(x=>`<article class="exercise-card is-visible"><div class="exercise-gif-wrap"><img src="${x[1]}" alt="${x[0]}" loading="lazy"></div><div class="exercise-copy"><h3>${x[0]}</h3><p>${g.description}</p><div class="exercise-metrics"><span>${x[2]}</span><span>${x[3]}</span></div></div></article>`).join('');};buttons.innerHTML=keys.map((k,i)=>`<button type="button" class="workout-group-button${i?'':' active'}" data-group="${k}">${WORKOUT_LIBRARY[k].label}</button>`).join('');buttons.addEventListener('click',e=>{const b=e.target.closest('.workout-group-button');if(b)render(b.dataset.group);});render(keys[0]);}
function showNotification(message,type='success'){document.querySelector('.notification')?.remove();const n=document.createElement('div');n.className=`notification notification-${type}`;n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.remove(),3500);}
